server:
  port: 8080

spring:
  application:
    name: bgsearch-project
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://49.247.43.17:3306/dnd_dev?autoReconnect=true
    username: jhjeon
    password: jun13576
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
---
mybatis:
  type-aliases-package: com.github.freshbread.mapper
  mapper-locations: mapper/*.xml

---
logging:
  config: classpath:logback.xml
  level:
    net:
      chndol:
        study:
          mybatissample:
            mapper: DEBUG
